youtubedl: vendor/rg3/youtube-dl/youtube_dl/__main__.py
python: /usr/bin/python
params:
    - --no-playlist
    - --no-warnings
    - --playlist-end
    - 1
convert: true
avconv: /usr/bin/ffmpeg
uglyUrls: false
stream: true
